# Generated by Django 5.2.6 on 2025-09-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_DB',
            fields=[
                ('brand_Name', models.CharField(max_length=10)),
                ('modelno', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_car', models.CharField(max_length=15)),
                ('manufacture_dob', models.DateField()),
                ('milage', models.FloatField()),
            ],
        ),
    ]
